[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/m0oXuL1VXs8uNyFPUxphK2Gw2rw_a2zM"

[etherscan]
base_sepolia = { key = "RQCKJ2RUXUBASPGW1W4MM4HW7VDF9VKURJ", url = "https://api-sepolia.basescan.org/api" } # Optional: For contract verification
